openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API documentation for the Contacts app.
tags:
  - name: Contacts
    description: Contacts related operations
servers:
  - url: http://127.0.0.1:8080
  - url: https://nodejs-hw-mongodb-kzxe.onrender.com
paths:
  /contact:
    get: 
      $ref: ../swagger/contacts/get.yaml
    post: 
      $ref: ../swager/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
